version: '3'
services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: vote-frontend
    volumes:
      - ./client:/usr/src/app/vote
      - /usr/src/app/vote/node_modules